
services:
  db:
    image: postgres:12    
    restart: always
    environment:
      - POSTGRES_USER=bloguser
      - POSTGRES_PASSWORD=blogpassword
      - POSTGRES_DB=blogdb
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  web:
    image: blog-to-dev:latest
    container_name: blog_cakephp_web
    restart: always
    ports:
      - "8181:80"
    volumes:
      - .:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  pgdata:
